apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: a0connections.kubernetes.auth0.com
spec:
  group: kubernetes.auth0.com
  names:
    kind: A0Connection
    listKind: A0ConnectionList
    plural: a0connections
    shortNames:
    - a0con
    singular: a0connection
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            properties:
              id:
                nullable: true
                type: string
              lastConf:
                nullable: true
                type: object
                x-kubernetes-preserve-unknown-fields: true
            type: object
          spec:
            properties:
              policy:
                items:
                  enum:
                  - Create
                  - Update
                  - Delete
                  type: string
                nullable: true
                type: array
              tenantRef:
                nullable: true
                properties:
                  namespace:
                    nullable: true
                    type: string
                  name:
                    nullable: true
                    type: string
                required:
                - name
                type: object
              find:
                nullable: true
                properties:
                  id:
                    nullable: true
                    type: string
                type: object
              init:
                nullable: true
                properties:
                  name:
                    nullable: true
                    type: string
                  display_name:
                    nullable: true
                    type: string
                  strategy:
                    nullable: true
                    type: string
                  options:
                    nullable: true
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  provisioning_ticket_url:
                    nullable: true
                    type: string
                  metadata:
                    nullable: true
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  realms:
                    items:
                      type: string
                    nullable: true
                    type: array
                  enabled_clients:
                    items:
                      properties:
                        namespace:
                          nullable: true
                          type: string
                        name:
                          nullable: true
                          type: string
                        id:
                          type: string
                      type: object
                      required:
                      - id
                    nullable: true
                    type: array
                    x-kubernetes-list-type: map
                    x-kubernetes-list-map-keys:
                    - id
                  show_as_button:
                    nullable: true
                    type: boolean
                  is_domain_connection:
                    nullable: true
                    type: boolean
                type: object
              conf:
                nullable: true
                properties:
                  name:
                    nullable: true
                    type: string
                  display_name:
                    nullable: true
                    type: string
                  strategy:
                    nullable: true
                    type: string
                  options:
                    nullable: true
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  provisioning_ticket_url:
                    nullable: true
                    type: string
                  metadata:
                    nullable: true
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  realms:
                    items:
                      type: string
                    nullable: true
                    type: array
                  enabled_clients:
                    items:
                      properties:
                        namespace:
                          nullable: true
                          type: string
                        name:
                          nullable: true
                          type: string
                        id:
                          type: string
                      type: object
                      required:
                      - id
                    nullable: true
                    type: array
                    x-kubernetes-list-type: map
                    x-kubernetes-list-map-keys:
                    - id
                  show_as_button:
                    nullable: true
                    type: boolean
                  is_domain_connection:
                    nullable: true
                    type: boolean
                type: object
            required:
            - tenantRef
            - conf
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}